VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.synced_folder "..", "/home/vagrant/python-nuclos"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
    end
end
