name: Ruff
on: [push, pull_request]

env:
  RUFF_VERSION: 0.11.4

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: ${{ env.RUFF_VERSION }}
          args: check --output-format=github
      - uses: astral-sh/ruff-action@v3
        with:
          version: ${{ env.RUFF_VERSION }}
          args: format --diff
